import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/navbar'
import Footer from '@/components/footer'
// import  icoin  from '../../public/images/logo.png'
import { StaticImageData } from 'next/image'

// type myIcon  = {
//   src:StaticImageData
// }
// const Favicon: myIcon = {src:icoin}


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'BawdicSoft',
  description: 'Generated by BawdicSoft',
  // icons: [{ rel: 'icon', url: Favicon.src.src }],
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
  <Navbar />
        
        {children}
  <Footer />
        
        </body>
    </html>
  )
}
